### ISSUE TITLE
Public repository and package with MIT license

### ISSUE THREAD

**Issue by stoiet** [emartech/node-backend-mock#1]
Hi!

I would like to make this project  - and also the NPM package - a public one with MIT license. This package is going to be a higher level wrapper above the [nock](https://github.com/node-nock/nock) library. Its goal is to help writing integration tests in a clearer way without prototype stubs, module mocks, etc.

The [nock](https://github.com/node-nock/nock) library is already used by other projects, but its API does not make integration testing easier. This project tries to solve this problem. It might be useful for several projects: suite-js-sdk, suite-service-js-sdk, email-campaign-distributor-service, maybe content-blocks-service, too.

Please review the request, @felin-arch and @drawain 

Thanks,
Robert Beretka

**Comment by felin-arch** [comment]
Seems like a great open-source candidate. Let's do it!

regards,
DAn
